// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameHistoricalPurchasing = "historical_purchasing"

// HistoricalPurchasing mapped from table <historical_purchasing>
type HistoricalPurchasing struct {
	ID          string    `gorm:"column:id;primaryKey" json:"id"`
	UserID      string    `gorm:"column:user_id;not null" json:"user_id"`
	ProductID   string    `gorm:"column:product_id;not null" json:"product_id"`
	Quantity    int32     `gorm:"column:quantity;not null" json:"quantity"`
	TotalPrice  float64   `gorm:"column:total_price;not null" json:"total_price"`
	PurchasedAt time.Time `gorm:"column:purchased_at;default:CURRENT_TIMESTAMP" json:"purchased_at"`
}

// TableName HistoricalPurchasing's table name
func (*HistoricalPurchasing) TableName() string {
	return TableNameHistoricalPurchasing
}
