// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProduct = "products"

// Product mapped from table <products>
type Product struct {
	ID            string    `gorm:"column:id;primaryKey" json:"id"`
	Name          string    `gorm:"column:name;not null" json:"name"`
	Brand         string    `gorm:"column:brand" json:"brand"`
	Description   string    `gorm:"column:description" json:"description"`
	Price         float64   `gorm:"column:price;not null" json:"price"`
	StockQuantity int32     `gorm:"column:stock_quantity" json:"stock_quantity"`
	CPU           string    `gorm:"column:cpu" json:"cpu"`
	RAM           string    `gorm:"column:ram" json:"ram"`
	Storage       string    `gorm:"column:storage" json:"storage"`
	Gpu           string    `gorm:"column:gpu" json:"gpu"`
	CreatedAt     time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName Product's table name
func (*Product) TableName() string {
	return TableNameProduct
}
